[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
evoter = "At2NcESoMB48ULsY7XPQFHAdjR1B5kEzfkP2Hk7WKrfD"

[programs.devnet]
evoter = "At2NcESoMB48ULsY7XPQFHAdjR1B5kEzfkP2Hk7WKrfD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
